import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const retron2000 = localFont({
  src: "../fonts/Retron2000.ttf",
  variable: "--font-retron",
})
const vcrOsdMono = localFont({
  src: "../fonts/VCR_OSD_MONO_1.001.ttf",
  variable: "--font-vcr",
})
const emoticonesTityly = localFont({
  src: "../fonts/EmoticonesTityly.ttf",
  variable: "--font-emoticones",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${retron2000.variable} ${vcrOsdMono.variable} ${emoticonesTityly.variable} font-retron`}
      >
        <div className="flex h-screen w-screen flex-col md:items-center">
          {children}
        </div>
      </body>
    </html>
  )
}
